version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - intervention-service
    networks:
      - app-network

  intervention-service:
    build: ./intervention
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/e4db
      - SALARIE_GRPC_URL=salarie-service:50051
    depends_on:
      - db
      - salarie-service
    networks:
      - app-network

  salarie-service:
    build: ./salarie
    ports:
      - "50051:50051"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/e4db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=e4db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
